In [2]:
import numpy as np
arr=np.array([1,2,3])
print(arr)
arr_2d=np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[1 2 3]
[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [4]:
import numpy as np
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [5]:
import numpy as np
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [6]:
import numpy as np
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
import numpy as np
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [8]:
import numpy as np
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [9]:
import numpy as np
np.random.rand(3,2)

array([[0.04670804, 0.59011623],
       [0.3630088 , 0.72629576],
       [0.20388568, 0.91842028]])

In [10]:
import numpy as np
np.random.randn(3,2)

array([[ 0.12813328, -0.99058904],
       [ 1.55583299, -0.15119419],
       [ 1.0989313 , -0.34722229]])

In [11]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)

(2, 3)


In [12]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.ndim)

2


In [13]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.size)

6


In [14]:
import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.dtype)

int64


In [17]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
a+b

array([5, 7, 9])

In [18]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
a*b

array([ 4, 10, 18])

In [19]:
import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

In [25]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)


array([[19, 22],
       [43, 50]])

In [26]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
A @ B

array([[19, 22],
       [43, 50]])

In [27]:
import numpy as np
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
np.dot(A, B)
A @ B

array([[19, 22],
       [43, 50]])

In [28]:
arr = np.array([1, 2, 3, 4])
arr.sum()

np.int64(10)

In [29]:
import numpy as np
arr = np.array([1, 2, 3, 4])
np.sum(arr)

np.int64(10)

In [30]:
arr = np.array([1, 2, 3, 4])
arr.mean()

np.float64(2.5)

In [31]:
arr = np.array([1, 2, 3, 4])
arr.max()

np.int64(4)

In [32]:
arr = np.array([1, 2, 3, 4])
arr.min()

np.int64(1)

In [33]:
arr = np.array([1, 2, 3, 4])
arr.std()

np.float64(1.118033988749895)

In [34]:
arr = np.array([1, 2, 3, 4, 5])
arr[0]

np.int64(1)

In [35]:
arr = np.array([1, 2, 3, 4, 5])
arr[1:4]

array([2, 3, 4])

In [39]:
arr = np.array([1, 2, 3, 4, 5])
arr[::2]

array([1, 3, 5])

In [44]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[0, 1]

np.int64(2)

In [47]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[:,1]

array([2, 5])

In [52]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
arr[1,:2]

array([4, 5])

In [56]:
arr = np.array([1, 2, 3, 4, 5])
mask = arr > 3
arr[mask]

array([4, 5])

In [57]:
arr = np.arange(6)
arr.reshape(2, 3)

array([[0, 1, 2],
       [3, 4, 5]])

In [58]:
a = np.array([1, 2])
b = np.array([3, 4])
np.concatenate((a, b))

array([1, 2, 3, 4])

In [59]:
a = np.array([1, 2])
b = np.array([3, 4])
np.vstack((a, b))

array([[1, 2],
       [3, 4]])

In [60]:
a = np.array([1, 2])
b = np.array([3, 4])
np.hstack((a, b))

array([1, 2, 3, 4])

In [61]:
a = np.array([1, 2, 3])
a + 5 # [6, 7, 8]

array([6, 7, 8])

In [62]:
np.save("array.npy", arr)

In [64]:
loaded_arr=np.load('array.npy')